# Generated by Django 5.0.2 on 2024-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0002_quantityvariant_sizevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='quantityvariant',
            old_name='color_code',
            new_name='variant_name',
        ),
        migrations.RemoveField(
            model_name='quantityvariant',
            name='color_name',
        ),
    ]
