# Generated by Django 5.0.2 on 2024-06-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0003_colorvariant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuantityVariant',
        ),
    ]
