# Generated by Django 5.0.2 on 2024-06-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0005_quantityvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocery_app1.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocery_app1.quantityvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocery_app1.sizevariant'),
        ),
    ]
