# Generated by Django 5.0.2 on 2024-06-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0006_product_color_variant_product_quantity_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image2',
        ),
    ]
