# Generated by Django 5.0.2 on 2025-02-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0007_alter_review_rating_reviewreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
