# Generated by Django 5.0.2 on 2024-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='no mail found', max_length=254),
        ),
    ]
