# Generated by Django 5.0.2 on 2024-07-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app1', '0011_alter_review_email_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
